#ifndef _KB_MACROS_DEFINE_H
#define _KB_MACROS_DEFINE_H

#define DEFAULT_KB_MACRO_0  KEY_A
#define DEFAULT_KB_MACRO_3  KEY_D
#define DEFAULT_KB_MACRO_4  KEY_E
#define DEFAULT_KB_MACRO_7  KEY_H
#define DEFAULT_KB_MACRO_8  KEY_I
#define DEFAULT_KB_MACRO_9  KEY_UP
#define DEFAULT_KB_MACRO_10 KEY_L
#define DEFAULT_KB_MACRO_11 KEY_M
#define DEFAULT_KB_MACRO_12 KEY_LEFT
#define DEFAULT_KB_MACRO_13 KEY_DOWN
#define DEFAULT_KB_MACRO_14 KEY_RIGHT
#define DEFAULT_KB_MACRO_15 KEY_Q

// ** NOTE: NOT CURRENTLY USED DUE TO MATRIX NOT ONLY HAVING 12 MACROS ** // 
#define DEFAULT_KB_MACRO_1  KEY_B
#define DEFAULT_KB_MACRO_2  KEY_C
#define DEFAULT_KB_MACRO_5  KEY_F
#define DEFAULT_KB_MACRO_6  KEY_G

#endif 