/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_EMBEDDEDMESSAGES_GIFFRAMEUPDATE_PB_H_INCLUDED
#define PB_EMBEDDEDMESSAGES_GIFFRAMEUPDATE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _GIFMessage_ColorSpace {
    GIFMessage_ColorSpace_BIT_24_RGB = 0,
    GIFMessage_ColorSpace_BIT_16_RGB = 1,
    GIFMessage_ColorSpace_BIT_48_RGB = 2,
    GIFMessage_ColorSpace_BIT_8_RGB = 3
} GIFMessage_ColorSpace;

/* Struct definitions */
typedef struct _GIFMessage {
    int32_t x_size;
    int32_t y_size;
    GIFMessage_ColorSpace color_space;
    int32_t message_size;
} GIFMessage;


/* Helper constants for enums */
#define _GIFMessage_ColorSpace_MIN GIFMessage_ColorSpace_BIT_24_RGB
#define _GIFMessage_ColorSpace_MAX GIFMessage_ColorSpace_BIT_8_RGB
#define _GIFMessage_ColorSpace_ARRAYSIZE ((GIFMessage_ColorSpace)(GIFMessage_ColorSpace_BIT_8_RGB+1))


/* Initializer values for message structs */
#define GIFMessage_init_default                  {0, 0, _GIFMessage_ColorSpace_MIN, 0}
#define GIFMessage_init_zero                     {0, 0, _GIFMessage_ColorSpace_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define GIFMessage_x_size_tag                    1
#define GIFMessage_y_size_tag                    2
#define GIFMessage_color_space_tag               3
#define GIFMessage_message_size_tag              4

/* Struct field encoding specification for nanopb */
#define GIFMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    x_size,            1) \
X(a, STATIC,   SINGULAR, INT32,    y_size,            2) \
X(a, STATIC,   SINGULAR, UENUM,    color_space,       3) \
X(a, STATIC,   SINGULAR, INT32,    message_size,      4)
#define GIFMessage_CALLBACK NULL
#define GIFMessage_DEFAULT NULL

extern const pb_msgdesc_t GIFMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GIFMessage_fields &GIFMessage_msg

/* Maximum encoded size of messages (where known) */
#define GIFMessage_size                          35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
