/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTO_PROGRAM_KEYBINDINGS_PB_H_INCLUDED
#define PB_PROTO_PROGRAM_KEYBINDINGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ProgramKeybindings_KeyType {
    ProgramKeybindings_KeyType_CTRL = 0,
    ProgramKeybindings_KeyType_SHIFT = 1,
    ProgramKeybindings_KeyType_ALT = 2,
    ProgramKeybindings_KeyType_GUI = 3,
    ProgramKeybindings_KeyType_LEFT_CTRL = 4,
    ProgramKeybindings_KeyType_LEFT_SHIFT = 5,
    ProgramKeybindings_KeyType_LEFT_ALT = 6,
    ProgramKeybindings_KeyType_LEFT_GUI = 7,
    ProgramKeybindings_KeyType_RIGHT_CTRL = 8,
    ProgramKeybindings_KeyType_RIGHT_SHIFT = 9,
    ProgramKeybindings_KeyType_RIGHT_ALT = 10,
    ProgramKeybindings_KeyType_RIGHT_GUI = 11,
    ProgramKeybindings_KeyType_SYSTEM_POWER_DOWN = 12,
    ProgramKeybindings_KeyType_SYSTEM_SLEEP = 13,
    ProgramKeybindings_KeyType_SYSTEM_WAKE_UP = 14,
    ProgramKeybindings_KeyType_PLAY = 15,
    ProgramKeybindings_KeyType_MEDIA_PAUSE = 16,
    ProgramKeybindings_KeyType_RECORD = 17,
    ProgramKeybindings_KeyType_FAST_FORWARD = 18,
    ProgramKeybindings_KeyType_REWIND = 19,
    ProgramKeybindings_KeyType_NEXT_TRACK = 20,
    ProgramKeybindings_KeyType_PREV_TRACK = 21,
    ProgramKeybindings_KeyType_STOP = 22,
    ProgramKeybindings_KeyType_EJECT = 23,
    ProgramKeybindings_KeyType_RANDOM_PLAY = 24,
    ProgramKeybindings_KeyType_PLAY_PAUSE = 25,
    ProgramKeybindings_KeyType_PLAY_SKIP = 26,
    ProgramKeybindings_KeyType_MUTE = 27,
    ProgramKeybindings_KeyType_VOLUME_INC = 28,
    ProgramKeybindings_KeyType_VOLUME_DEC = 29,
    ProgramKeybindings_KeyType_A = 30,
    ProgramKeybindings_KeyType_B = 31,
    ProgramKeybindings_KeyType_C = 32,
    ProgramKeybindings_KeyType_D = 33,
    ProgramKeybindings_KeyType_E = 34,
    ProgramKeybindings_KeyType_F = 35,
    ProgramKeybindings_KeyType_G = 36,
    ProgramKeybindings_KeyType_H = 37,
    ProgramKeybindings_KeyType_I = 38,
    ProgramKeybindings_KeyType_J = 39,
    ProgramKeybindings_KeyType_K = 40,
    ProgramKeybindings_KeyType_L = 41,
    ProgramKeybindings_KeyType_M = 42,
    ProgramKeybindings_KeyType_N = 43,
    ProgramKeybindings_KeyType_O = 44,
    ProgramKeybindings_KeyType_P = 45,
    ProgramKeybindings_KeyType_Q = 46,
    ProgramKeybindings_KeyType_R = 47,
    ProgramKeybindings_KeyType_S = 48,
    ProgramKeybindings_KeyType_T = 49,
    ProgramKeybindings_KeyType_U = 50,
    ProgramKeybindings_KeyType_V = 51,
    ProgramKeybindings_KeyType_W = 52,
    ProgramKeybindings_KeyType_X = 53,
    ProgramKeybindings_KeyType_Y = 54,
    ProgramKeybindings_KeyType_Z = 55,
    ProgramKeybindings_KeyType_KEY_1 = 56,
    ProgramKeybindings_KeyType_KEY_2 = 57,
    ProgramKeybindings_KeyType_KEY_3 = 58,
    ProgramKeybindings_KeyType_KEY_4 = 59,
    ProgramKeybindings_KeyType_KEY_5 = 60,
    ProgramKeybindings_KeyType_KEY_6 = 61,
    ProgramKeybindings_KeyType_KEY_7 = 62,
    ProgramKeybindings_KeyType_KEY_8 = 63,
    ProgramKeybindings_KeyType_KEY_9 = 64,
    ProgramKeybindings_KeyType_KEY_0 = 65,
    ProgramKeybindings_KeyType_ENTER = 66,
    ProgramKeybindings_KeyType_ESC = 67,
    ProgramKeybindings_KeyType_BACKSPACE = 68,
    ProgramKeybindings_KeyType_TAB = 69,
    ProgramKeybindings_KeyType_SPACE = 70,
    ProgramKeybindings_KeyType_MINUS = 71,
    ProgramKeybindings_KeyType_EQUAL = 72,
    ProgramKeybindings_KeyType_LEFT_BRACE = 73,
    ProgramKeybindings_KeyType_RIGHT_BRACE = 74,
    ProgramKeybindings_KeyType_BACKSLASH = 75,
    ProgramKeybindings_KeyType_NON_US_NUM = 76,
    ProgramKeybindings_KeyType_SEMICOLON = 77,
    ProgramKeybindings_KeyType_QUOTE = 78,
    ProgramKeybindings_KeyType_TILDE = 79,
    ProgramKeybindings_KeyType_COMMA = 80,
    ProgramKeybindings_KeyType_PERIOD = 81,
    ProgramKeybindings_KeyType_SLASH = 82,
    ProgramKeybindings_KeyType_CAPS_LOCK = 83,
    ProgramKeybindings_KeyType_F1 = 84,
    ProgramKeybindings_KeyType_F2 = 85,
    ProgramKeybindings_KeyType_F3 = 86,
    ProgramKeybindings_KeyType_F4 = 87,
    ProgramKeybindings_KeyType_F5 = 88,
    ProgramKeybindings_KeyType_F6 = 89,
    ProgramKeybindings_KeyType_F7 = 90,
    ProgramKeybindings_KeyType_F8 = 91,
    ProgramKeybindings_KeyType_F9 = 92,
    ProgramKeybindings_KeyType_F10 = 93,
    ProgramKeybindings_KeyType_F11 = 94,
    ProgramKeybindings_KeyType_F12 = 95,
    ProgramKeybindings_KeyType_PRINTSCREEN = 96,
    ProgramKeybindings_KeyType_SCROLL_LOCK = 97,
    ProgramKeybindings_KeyType_KEY_PAUSE = 98,
    ProgramKeybindings_KeyType_INSERT = 99,
    ProgramKeybindings_KeyType_HOME = 100,
    ProgramKeybindings_KeyType_PAGE_UP = 101,
    ProgramKeybindings_KeyType_DELETE = 102,
    ProgramKeybindings_KeyType_END = 103,
    ProgramKeybindings_KeyType_PAGE_DOWN = 104,
    ProgramKeybindings_KeyType_RIGHT = 105,
    ProgramKeybindings_KeyType_LEFT = 106,
    ProgramKeybindings_KeyType_DOWN = 107,
    ProgramKeybindings_KeyType_UP = 108,
    ProgramKeybindings_KeyType_NUM_LOCK = 109,
    ProgramKeybindings_KeyType_PAD_SLASH = 110,
    ProgramKeybindings_KeyType_PAD_ASTERIX = 111,
    ProgramKeybindings_KeyType_PAD_MINUS = 112,
    ProgramKeybindings_KeyType_PAD_PLUS = 113,
    ProgramKeybindings_KeyType_PAD_ENTER = 114,
    ProgramKeybindings_KeyType_PAD_1 = 115,
    ProgramKeybindings_KeyType_PAD_2 = 116,
    ProgramKeybindings_KeyType_PAD_3 = 117,
    ProgramKeybindings_KeyType_PAD_4 = 118,
    ProgramKeybindings_KeyType_PAD_5 = 119,
    ProgramKeybindings_KeyType_PAD_6 = 120,
    ProgramKeybindings_KeyType_PAD_7 = 121,
    ProgramKeybindings_KeyType_PAD_8 = 122,
    ProgramKeybindings_KeyType_PAD_9 = 123,
    ProgramKeybindings_KeyType_PAD_0 = 124,
    ProgramKeybindings_KeyType_PAD_PERIOD = 125,
    ProgramKeybindings_KeyType_NON_US_BS = 126,
    ProgramKeybindings_KeyType_MENU = 127,
    ProgramKeybindings_KeyType_F13 = 128,
    ProgramKeybindings_KeyType_F14 = 129,
    ProgramKeybindings_KeyType_F15 = 130,
    ProgramKeybindings_KeyType_F16 = 131,
    ProgramKeybindings_KeyType_F17 = 132,
    ProgramKeybindings_KeyType_F18 = 133,
    ProgramKeybindings_KeyType_F19 = 134,
    ProgramKeybindings_KeyType_F20 = 135,
    ProgramKeybindings_KeyType_F21 = 136,
    ProgramKeybindings_KeyType_F22 = 137,
    ProgramKeybindings_KeyType_F23 = 138,
    ProgramKeybindings_KeyType_F24 = 139
} ProgramKeybindings_KeyType;

/* Struct definitions */
typedef struct _ProgramKeybindings {
    ProgramKeybindings_KeyType macro_zero;
    ProgramKeybindings_KeyType macro_one;
    ProgramKeybindings_KeyType macro_two;
    ProgramKeybindings_KeyType macro_three;
    ProgramKeybindings_KeyType macro_four;
    ProgramKeybindings_KeyType macro_five;
    ProgramKeybindings_KeyType macro_six;
    ProgramKeybindings_KeyType macro_seven;
    ProgramKeybindings_KeyType macro_eight;
    ProgramKeybindings_KeyType macro_nine;
    ProgramKeybindings_KeyType macro_ten;
    ProgramKeybindings_KeyType macro_eleven;
    ProgramKeybindings_KeyType macro_twelve;
    ProgramKeybindings_KeyType macro_thirteen;
    ProgramKeybindings_KeyType macro_fourteen;
    ProgramKeybindings_KeyType macro_fifteen;
    bool return_message;
} ProgramKeybindings;


/* Helper constants for enums */
#define _ProgramKeybindings_KeyType_MIN ProgramKeybindings_KeyType_CTRL
#define _ProgramKeybindings_KeyType_MAX ProgramKeybindings_KeyType_F24
#define _ProgramKeybindings_KeyType_ARRAYSIZE ((ProgramKeybindings_KeyType)(ProgramKeybindings_KeyType_F24+1))


/* Initializer values for message structs */
#define ProgramKeybindings_init_default          {_ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, 0}
#define ProgramKeybindings_init_zero             {_ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, _ProgramKeybindings_KeyType_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ProgramKeybindings_macro_zero_tag        1
#define ProgramKeybindings_macro_one_tag         2
#define ProgramKeybindings_macro_two_tag         3
#define ProgramKeybindings_macro_three_tag       4
#define ProgramKeybindings_macro_four_tag        5
#define ProgramKeybindings_macro_five_tag        6
#define ProgramKeybindings_macro_six_tag         7
#define ProgramKeybindings_macro_seven_tag       8
#define ProgramKeybindings_macro_eight_tag       9
#define ProgramKeybindings_macro_nine_tag        10
#define ProgramKeybindings_macro_ten_tag         11
#define ProgramKeybindings_macro_eleven_tag      12
#define ProgramKeybindings_macro_twelve_tag      13
#define ProgramKeybindings_macro_thirteen_tag    14
#define ProgramKeybindings_macro_fourteen_tag    15
#define ProgramKeybindings_macro_fifteen_tag     16
#define ProgramKeybindings_return_message_tag    17

/* Struct field encoding specification for nanopb */
#define ProgramKeybindings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    macro_zero,        1) \
X(a, STATIC,   SINGULAR, UENUM,    macro_one,         2) \
X(a, STATIC,   SINGULAR, UENUM,    macro_two,         3) \
X(a, STATIC,   SINGULAR, UENUM,    macro_three,       4) \
X(a, STATIC,   SINGULAR, UENUM,    macro_four,        5) \
X(a, STATIC,   SINGULAR, UENUM,    macro_five,        6) \
X(a, STATIC,   SINGULAR, UENUM,    macro_six,         7) \
X(a, STATIC,   SINGULAR, UENUM,    macro_seven,       8) \
X(a, STATIC,   SINGULAR, UENUM,    macro_eight,       9) \
X(a, STATIC,   SINGULAR, UENUM,    macro_nine,       10) \
X(a, STATIC,   SINGULAR, UENUM,    macro_ten,        11) \
X(a, STATIC,   SINGULAR, UENUM,    macro_eleven,     12) \
X(a, STATIC,   SINGULAR, UENUM,    macro_twelve,     13) \
X(a, STATIC,   SINGULAR, UENUM,    macro_thirteen,   14) \
X(a, STATIC,   SINGULAR, UENUM,    macro_fourteen,   15) \
X(a, STATIC,   SINGULAR, UENUM,    macro_fifteen,    16) \
X(a, STATIC,   SINGULAR, BOOL,     return_message,   17)
#define ProgramKeybindings_CALLBACK NULL
#define ProgramKeybindings_DEFAULT NULL

extern const pb_msgdesc_t ProgramKeybindings_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ProgramKeybindings_fields &ProgramKeybindings_msg

/* Maximum encoded size of messages (where known) */
#define ProgramKeybindings_size                  52

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
