/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3-dev */

#ifndef PB_PROTO_IMAGE_FLASH_PB_H_INCLUDED
#define PB_PROTO_IMAGE_FLASH_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ImageFlash {
    uint32_t x_len;
    uint32_t y_len;
    uint32_t image_size;
    uint32_t pixel_size;
    uint32_t flash_space;
    bool display_now;
} ImageFlash;


/* Initializer values for message structs */
#define ImageFlash_init_default                  {0, 0, 0, 0, 0, 0}
#define ImageFlash_init_zero                     {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ImageFlash_x_len_tag                     1
#define ImageFlash_y_len_tag                     2
#define ImageFlash_image_size_tag                3
#define ImageFlash_pixel_size_tag                4
#define ImageFlash_flash_space_tag               5
#define ImageFlash_display_now_tag               6

/* Struct field encoding specification for nanopb */
#define ImageFlash_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x_len,             1) \
X(a, STATIC,   SINGULAR, UINT32,   y_len,             2) \
X(a, STATIC,   SINGULAR, UINT32,   image_size,        3) \
X(a, STATIC,   SINGULAR, UINT32,   pixel_size,        4) \
X(a, STATIC,   SINGULAR, UINT32,   flash_space,       5) \
X(a, STATIC,   SINGULAR, BOOL,     display_now,       6)
#define ImageFlash_CALLBACK NULL
#define ImageFlash_DEFAULT NULL

extern const pb_msgdesc_t ImageFlash_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ImageFlash_fields &ImageFlash_msg

/* Maximum encoded size of messages (where known) */
#define ImageFlash_size                          32

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
